package_assets: on
embed_assets: off
compress_assets: on
javascript_compressor: yui
gzip_assets: off

javascripts:
  defaults:
    - public/javascripts/jquery.min.js
    - public/javascripts/bootstrap.min.js
    - public/javascripts/jquery.inlineedit.js
    - public/javascripts/jquery-ui-1.9.0.custom.min.js
    - public/javascripts/rails.js
    - public/javascripts/spectrum.js
    - public/javascripts/app.js

stylesheets:
  defaults:
    - public/stylesheets/app.css
    - public/stylesheets/spectrum.css
